import React from 'react'
import { notFound } from 'next/navigation'
import { Noto_Kufi_Arabic } from 'next/font/google'

import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import clx from 'clsx'

import type { Metadata } from 'next'
import '@/app/globals.css'

const notoKufiArabic = Noto_Kufi_Arabic({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['arabic', 'latin'],
})

export const metadata: Metadata = {
  title: 'Aqarat',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()
  if (!locale) return notFound()

  return (
    <html
      lang="en"
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
    >
      <NextIntlClientProvider messages={messages}>
        <body className={clx('antialiased', notoKufiArabic.className)}>{children}</body>
      </NextIntlClientProvider>
    </html>
  )
}
